version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: api_sidebar
    depends_on:
      - database
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    networks:
      - sidebar-network

  mysql:
    image: mysql:5.7
    container_name: database_sidebar
    restart: always
    ports:
      - "3307:3306"
    env_file:
      - ./src/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql/
    networks:
      - sidebar-network

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - sidebar-network

  kafka:
    image: docker.io/bitnami/kafka:3.2
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - sidebar-network

networks:
  sidebar-network:

volumes:
  mysql_data:
    driver: local
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local